# Generated by Django 2.1.7 on 2020-08-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '패스트캠퍼스\xa0사용자', 'verbose_name_plural': '패스트캠퍼스\xa0사용자'},
        ),
    ]
