# Generated by Django 2.1.7 on 2020-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20200820_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='testEmail',
            field=models.EmailField(default='test@test.com', max_length=128, verbose_name='사용자이메일1'),
            preserve_default=False,
        ),
    ]
