# Generated by Django 2.1.7 on 2020-08-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0004_fcuser_testemail2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcuser',
            name='testEmail',
        ),
        migrations.RemoveField(
            model_name='fcuser',
            name='testEmail2',
        ),
    ]
